# Generated by Django 5.0.7 on 2024-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
