# Generated by Django 5.0.7 on 2024-08-15 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_userstatus_is_typing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstatus",
            name="is_typing",
        ),
    ]
