import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/storeProvider";
import Navbar from "@/app/@navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
   navbar,
}: Readonly<{
  children: React.ReactNode;
    navbar: React.ReactNode;
}>) {
  return (
          <StoreProvider>
              <html lang="en">
              <body className={inter.className + " bg-gray-300"} style={{height:"100vh",width:"100%",maxHeight:"100vh"} }>
              {navbar}
              {children}
              </body>
                </html>
          </StoreProvider>
  );
}
