import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/Navbar";
import StoreProvider from "@/lib/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <StoreProvider>

          <html lang="en">
          <body className={inter.className} style={{height:"100vh",width:"100%",maxHeight:"100vh"}}>
          <Navbar/>
          {children}</body>
            </html>
      </StoreProvider>
  );
}
