"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/storeProvider";
import Navbar from "@/app/_components/Navbar/Navbar";
import {Container} from "@mui/material";
import {ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


    function showNavIcons(e,icons_count:number){
        for (let i = 1; i <= icons_count; i++) {
            const nav_icons = document.getElementById(`nav_icons_${i}`)
            if(e.target===nav_icons) {
                nav_icons.nextElementSibling.classList.toggle('hidden')
            }else if(!e.target.classList.contains('nav_icons_'+i) ) {  // &&  !e.target.closest(`.nav_icons_${i}`) to check if the target is not the icon or its children
                nav_icons.nextElementSibling?.classList.add('hidden')
            }
        }
    }
  return (
          <StoreProvider>
              <html lang="en">
              <body onClick={e=>showNavIcons(e,2)} className={inter.className + " bg-gray-300"} style={{height:"100vh",width:"100%",maxHeight:"100vh"} }>
              <Navbar />
              <Container>
                {children}
              </Container>

              <ToastContainer />
              </body>
                </html>
          </StoreProvider>
  );
}
