# Generated by Django 5.0.7 on 2024-07-10 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublicChat",
            new_name="PublicChatModel",
        ),
    ]
