# Generated by Django 5.0.7 on 2024-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0002_rename_publicchat_publicchatmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicchatmodel",
            name="user_id",
            field=models.CharField(default="anonymous", max_length=100),
        ),
    ]
