# Generated by Django 5.0.7 on 2024-07-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0004_publicchatmessagesmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicchatmodel",
            name="messages",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="public_chat.publicchatmessagesmodel",
            ),
        ),
    ]
