# Generated by Django 5.0.7 on 2024-07-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0006_remove_publicchatmodel_messages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicchatmessagesmodel",
            name="messages",
        ),
        migrations.AddField(
            model_name="publicchatmessagesmodel",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="public_chat.publicchatmodel",
            ),
        ),
    ]
