# Generated by Django 5.0.7 on 2024-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0008_publicchatroom_publicchatroommessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicchatroom",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
