# Generated by Django 5.0.7 on 2024-08-05 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("public_chat", "0009_publicchatroom_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublicChatRoom",
            new_name="PublicChatModel",
        ),
    ]
