# Generated by Django 5.0.7 on 2024-08-17 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="read_by",
        ),
    ]
