# Generated by Django 5.0.7 on 2024-08-18 11:35

import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_remove_groupmessage_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmodel",
            name="image",
            field=models.ImageField(
                blank=True,
                default="groups/default_group.jpg",
                null=True,
                upload_to=groups.models.group_image_path,
            ),
        ),
    ]
