# Generated by Django 5.0.7 on 2024-08-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_groupmodel_image_groupmessagestatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmessagestatus",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
