# Generated by Django 5.0.7 on 2024-08-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_groupmessagestatus_read_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmodel",
            name="last_message_timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
