# Generated by Django 5.0.7 on 2024-08-06 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("private_chat", "0004_alter_privatechatmessagemodel_chat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatechatmessagemodel",
            old_name="content",
            new_name="message",
        ),
    ]
