# Generated by Django 5.0.7 on 2024-08-08 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("private_chat", "0006_privatechatmodel_last_message_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatechatmodel",
            options={"ordering": ["-last_message_timestamp"]},
        ),
    ]
