# Generated by Django 5.0.7 on 2024-08-08 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("private_chat", "0007_alter_privatechatmodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatechatmodel",
            options={},
        ),
    ]
