# Generated by Django 5.0.7 on 2024-08-10 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("private_chat", "0010_privatechatmessagereadstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privatechatmodel",
            old_name="is_active",
            new_name="active",
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 10, 18, 32, 31, 989136, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privatechatmessagemodel",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="privatechatmessagemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 10, 18, 32, 33, 406158, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privatechatmessagemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privatechatmessagereadstatus",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="privatechatmessagereadstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 10, 18, 32, 34, 636015, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privatechatmessagereadstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privatechatmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
