# Generated by Django 5.0.7 on 2024-08-10 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("private_chat", "0011_rename_is_active_privatechatmodel_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatparticipant",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="privatechatmessagemodel",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="privatechatmessagereadstatus",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="privatechatmodel",
            old_name="active",
            new_name="is_active",
        ),
    ]
