# Generated by Django 5.0.7 on 2024-08-10 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_alter_friendlist_friends_alter_friendlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 10, 19, 4, 40, 115569, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
